apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "project.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        chart: {{ template "project.fullname" . }}
        app: test
    spec:
      containers:
      - name: test
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
