apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    chart: {{ template "project.fullname" . }}
    app: test
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30009